import "@/styles/globals.css";

import os from "node:os";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Link from "next/link";

import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/utils/styles";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { username } = os.userInfo();

  return (
    <html
      lang="en"
      className={cn(GeistSans.variable, "h-full overflow-x-hidden")}
    >
      <body className="bg-background text-foreground flex h-full flex-col justify-between">
        <header className="container mx-auto py-6">
          <nav className="flex justify-between">
            <Link href="/">
              <div className="font-light">epic</div>
              <div className="font-bold">notes</div>
            </Link>
            <Link className="underline" href="users/kody/notes">
              Kody`s Notes
            </Link>
          </nav>
        </header>

        <TRPCReactProvider>
          <main className="flex-1">{children}</main>
        </TRPCReactProvider>

        <div className="container mx-auto flex justify-between">
          <Link href="/">
            <div className="font-light">epic</div>
            <div className="font-bold">notes</div>
          </Link>
          <p>Built with ♥️ by {username}</p>
        </div>
      </body>
    </html>
  );
}
